[package]
name = "black_scholes_pricer"
version = "0.1.0"
authors = ["ronnie chowdhury <ronnie.c995@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wide= "^0.5"
bytemuck = "^1"

[profile.dev]
opt-level = 0
debug = 2

[profile.release]
opt-level = 3
debug = 0